from sqlalchemy.orm import Session

from database import get_user_by_email

# some values AI autogenerated
def test_register_user_success(client, db_session: Session):
    payload = {
        "username": "madison",
        "email": "madison@example.com",
        "password": "pw12345",
    }

    resp = client.post("/api/register", json=payload)
    assert resp.status_code == 200

    data = resp.json()
    assert data["username"] == "madison"
    assert data["email"] == "madison@example.com"
    assert data["token"] == "(cookie)"
    assert "auth_token" in resp.cookies

    # Verify row created
    user = get_user_by_email(db_session, "madison@example.com")
    assert user is not None
    assert user.username == "madison"


def test_register_duplicate_email(client):
    payload = {
        "username": "user1",
        "email": "dup@example.com",
        "password": "pw",
    }
    # first time
    r1 = client.post("/api/register", json=payload)
    assert r1.status_code == 200

    # second time should fail
    r2 = client.post("/api/register", json=payload)
    assert r2.status_code == 400


def test_login_success(client):
    # create account first
    client.post(
        "/api/register",
        json={
            "username": "loginuser",
            "email": "login@example.com",
            "password": "pw",
        },
    )

    resp = client.post(
        "/api/login",
        json={
            "email": "login@example.com",
            "password": "pw",
        },
    )
    assert resp.status_code == 200
    assert "auth_token" in resp.cookies


def test_login_invalid_credentials(client):
    resp = client.post(
        "/api/login",
        json={
            "email": "nosuch@example.com",
            "password": "pw",
        },
    )
    assert resp.status_code == 401


def test_me_requires_auth(client):
    resp = client.get("/api/me")
    assert resp.status_code == 401


def test_me_with_cookie(client):
    # register -> cookie stored in client
    resp_reg = client.post(
        "/api/register",
        json={
            "username": "meuser",
            "email": "me@example.com",
            "password": "pw",
        },
    )
    assert resp_reg.status_code == 200

    resp = client.get("/api/me")
    assert resp.status_code == 200

    data = resp.json()
    assert data["username"] == "meuser"
    assert data["email"] == "me@example.com"


def test_logout_clears_cookie(client):
    client.post(
        "/api/register",
        json={
            "username": "logoutuser",
            "email": "logout@example.com",
            "password": "pw",
        },
    )

    resp = client.post("/api/logout")
    assert resp.status_code == 200

    # AI suggested checking cookie cleared
    assert "auth_token" not in resp.cookies
