from sqlalchemy.orm import Session

from database import Question, list_attempts_for_user

# some values AI autogenerated
# I will probably change this so that submit attempt does not require auth
def test_submit_attempt_requires_auth(client):
    resp = client.post(
        "/api/attempts",
        json={"question_id": 1, "user_answer": "2"},
    )
    assert resp.status_code == 401


def test_submit_attempt_success(client, db_session: Session, override_require_user):
    user = override_require_user  

    q = Question(
        topic_id=1,
        text="1+1?",
        difficulty=1,
        solution="2",
    )
    db_session.add(q)
    db_session.commit()
    db_session.refresh(q)

    resp = client.post(
        "/api/attempts",
        json={"question_id": q.id, "user_answer": "2"},
    )
    assert resp.status_code == 200

    data = resp.json()
    assert data["correct"] is True

    # Verify attempt recorded
    attempts = list_attempts_for_user(db_session, user_id=user.id, limit=10)
    assert len(attempts) == 1
    assert attempts[0].question_id == q.id
    assert attempts[0].correct is True


def test_submit_attempt_question_not_found(client, override_require_user):
    _ = override_require_user  # just to ensure auth

    resp = client.post(
        "/api/attempts",
        json={"question_id": 999999, "user_answer": "anything"},
    )
    assert resp.status_code == 404
